### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/gleam#32]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [x] [Configure online editor](https://github.com/exercism/gleam/issues/23)
- [x] [Add key features](https://github.com/exercism/gleam/issues/24)
- [x] [Add tags](https://github.com/exercism/gleam/issues/25)
- [x] [Add prerequisites to Practice Exercises](https://github.com/exercism/gleam/issues/26)
- [x] [Update status of track](https://github.com/exercism/gleam/issues/30)
- [x] [Update status of Concept Exercises](https://github.com/exercism/gleam/issues/31)
- [x] [Pass linting checks](https://github.com/exercism/gleam/issues/27)
- [x] [Build Test Runner](https://github.com/exercism/gleam/issues/28)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/gleam/issues/29) (optional)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7

**Comment by lpil** [comment]
Hi @ErikSchierboom ! What's the recommended number of practice exercises to have prior to launch?

**Comment by ErikSchierboom** [comment]
@lpil 20-ish. I've just checked, and there are 24 already:

```shell
erik@schierheim:~/exercism/gleam$ jq '[.exercises.practice[] | select(.status == null or .status == "active")] | length'  config.json
24
```

**Comment by lpil** [comment]
Fab! Is there anything left to do?

**Comment by ErikSchierboom** [comment]
Nothing that blocks launching I think! 🎉 

Looking at the [new tracks docs](https://exercism.org/docs/building/tracks/new), after launching the track, I think the next steps would be:

1. Add more practice exercises
2. Configure lines of code counter (https://exercism.org/docs/building/tracks/new/configure-tooling)
3. Configure snippet extractor (https://exercism.org/docs/building/tracks/new/configure-tooling)
4. Create highlightjs plugin
5. Create codemirror plugin
6. Build representer (will only really become useful once you have a fair number of submitted solutions)
7. Build analyzer

The first one is the most important one, but you might want to choose other steps to work on in parallel. From a student's viewpoint, the highlightjs plugin and codemirror plugins are probably the most impactful ones. We have people that have built these plugins for other tracks, so feel free to ask for help on the forum.

**Comment by lpil** [comment]
Wonderful! Thank you!

**Comment by ErikSchierboom** [comment]
@lpil Is there anything you'd like to do before going live? From my viewpoint, we're ready!

**Comment by lpil** [comment]
All good to go I think! 🥳

**Comment by ErikSchierboom** [comment]
@lpil Then I'd like to give you the honor of opening the PR to set the `active` property to `true` in the `config.json` file.

**Comment by lpil** [comment]
@ErikSchierboom There is a highlightjs plugin for Gleam [here on npm](https://www.npmjs.com/package/@gleam-lang/highlight.js-gleam)

**Comment by lpil** [comment]
I've had a look at the lines of code counter repo and I believe there is nothing to do for Gleam as the test module path is in specified in the config json file.

**Comment by ErikSchierboom** [comment]
> There is a highlightjs plugin for Gleam [here on npm](https://www.npmjs.com/package/@gleam-lang/highlight.js-gleam)

I'll get that sorted out next week

> I've had a look at the lines of code counter repo and I believe there is nothing to do for Gleam as the test module path is in specified in the config json file.

You're right, it is indeed listed in the supported languages: https://github.com/XAMPPRocky/tokei/blob/master/languages.json

**Comment by ErikSchierboom** [comment]
@lpil PR opened: https://github.com/exercism/website/pull/3411
